// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompletedGoalsController from "./completed_goals_controller"
application.register("completed-goals", CompletedGoalsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import QuotesController from "./quotes_controller"
application.register("quotes", QuotesController)

import WellDoneModalController from "./well_done_modal_controller"
application.register("well-done-modal", WellDoneModalController)
